package net.estemon.studio.assets;

public class AssetPaths {
    private AssetPaths() {} // not instantiable

    public static final String GAMEPLAY_ATLAS = "gameplay.atlas";

    // Music by xsgianni from https://freesound.org/people/xsgianni/sounds/388079/
    // CC BY-NC 4.0 DEED https://creativecommons.org/licenses/by-nc/4.0/
    public static final String GAME_MUSIC = "sounds/game_music.mp3";

    // Sound generated by https://www.audiogen.co/
    // Prompt: "a loopable plane single propeller engine sound"
    public static final String SOUND_PROPELLER = "sounds/propeller2.mp3";
}
